### ISSUE TITLE
cmp-tabnine gets automatically loaded before cmp itself

### ISSUE THREAD

**Issue by j-ilden** [lewis6991/impatient.nvim#43] opened 2021-12-22 00:45 UTC
See my issue here. https://github.com/tzachar/cmp-tabnine/issues/32

tzachar/cmp-tabnine can't be installed when impatient.vim is enabled. No matter how often you clear or rebuild cache. It requires cmp_tabnine.config to be loaded. Impatient loads tabnine earlier than cmp for a reason I could not find.

If you have an auto reload of Packer upon save of your config file, Packer won 't reload properly before installation. I have resolved the installation issue with my pull request to tabnine above.

But there needs to be a rule set for this in impatient. I couldn't figure out how, and documentation didn't help me either. Maybe it's me, but it will definitely be someone else as well.

**Comment by lewis6991** [comment] 2021-12-22 09:08
Can you please provide some form of reproducible minimal testcase?

From what you have said, it sounds like the issue isn't related to impatient.

> Impatient loads tabnine earlier than cmp for a reason I could not find.

Impatient doesn't change the order or when a module is loaded, it just caches the modules bytecode when it is loaded.

If impatient can't find the module, then it will default to the original loader.

**Comment by lewis6991** [comment] 2022-02-10 21:42
Closing, but will reopen if this is still an issue.

**Closed as completed by lewis6991** 2022-02-10 21:42 UTC
