### ISSUE TITLE
impatient.lua:243: attempt to call field 'encode' (a  nil value)

### ISSUE THREAD

**Issue by ayoubelmhamdi** [lewis6991/impatient.nvim#40] opened 2021-11-03 01:11 UTC
with the new update of this plugin,i get this error when I open `neovim`
```log
Error detected while processing VimEnter Autocommands for "*":
E5108: Error executing lua .../site/pack/packer/start/impatient.nvim/lua/impatient.lua:243: attempt to call field 'encode' (a
 nil value)
```
when I open neovim, I get this error
I'm in Linux: `Void-linux`
nvim version: `NVIM v0.6.0-dev+a5d6f36`
this error come from this function
```lua
function M.save_cache()
  if M.dirty then
    log('Updating cache file: %s', M.path)
    local f = io.open(M.path, 'w+b')
    f:write(mpack.encode(M.cache))
    f:flush()
    M.dirty = false
  end
end
```
when go back to to commit `561b86e` I see that I should be 
```diff
-      f:write(mpack.encode(M.cache))
+      f:write(mpack.pack(M.cache))

-      return mpack.unpack(f:read'*a')
+      return mpack.decode(f:read'*a')

```

**Comment by clason** [comment] 2021-11-03 08:12
You have to upgrade your Neovim version to the latest HEAD, see https://github.com/neovim/neovim/issues/14090#issuecomment-955239489.

**Comment by clason** [comment] 2021-11-03 08:13
(If you run the nightly pre-release, you _have_ to constantly keep it updated, or things _will_ break.)

**Comment by lewis6991** [comment] 2021-11-03 08:57
Duplicate of #38

**Closed as completed** 2021-11-03 08:57 UTC
Labels: duplicate

**Comment by lewis6991** [comment] 2021-11-03 10:21
27c783556dd3e4085a0a93063f242c888405d6b6 should stop old 0.6-dev installs breaking, though it is still recommended you upgrade to latest master or roll back to 0.5
